services:
  - type: web
    name: efata-backend
    env: docker
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: DOCKER_ENABLE_BUILDKIT
        value: "1"
    healthCheckPath: /api/health
